version: '3.4'

services:
  eblog:
    image: ${DOCKER_REGISTRY-}eblog
    build:
      context: .
      dockerfile: EBlog/Dockerfile
    ports:
     - '80:80'

  postgres:
    container_name: postgres
    build: ./db
    ports:
     - '5432:5432'
